{{ if  .Values.elasticsearch.config.usePassword  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skywalking.fullname" . }}-elasticsearch
  labels:
    app: {{ template "skywalking.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.oap.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.elasticsearch.config.password | b64enc | quote }}
{{- end }}
